version: '3.8'

services:
  shell:
    build:
      context: ./apps/shell
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_GRAPHQL_ENDPOINT=http://backend:4000/graphql
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - REGION=us-east-1
      - TABLE_NAME=aws-micro-frontend-backend-main-local
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      - dynamodb
    networks:
      - app-network

  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/home/dynamodblocal/data"]
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./data/dynamodb:/home/dynamodblocal/data
    networks:
      - app-network

  dynamo-admin:
    build:
      context: ./apps/dynamo-admin
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=us-east-1
      - DYNAMO_ENDPOINT=http://dynamodb:8000
    depends_on:
      - dynamodb
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - shell
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
