service: aws-micro-frontend-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    USERS_TABLE: ${self:service}-users-${self:provider.stage}
    DASHBOARD_TABLE: ${self:service}-dashboard-${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:service}-*"
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"

functions:
  graphql:
    handler: dist/handlers/graphql.handler
    events:
      - http:
          path: /graphql
          method: ANY
          cors: true
    environment:
      GRAPHQL_ENDPOINT: https://${self:service}-${self:provider.stage}.${self:provider.region}.amazonaws.com/graphql

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dynamodb-local

custom:
  serverless-offline:
    httpPort: 4000
    host: 0.0.0.0
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
    stages:
      - dev
      - local

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

    DashboardTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DASHBOARD_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

  Outputs:
    GraphQLEndpoint:
      Value: !GetAtt GraphqlLambdaFunction.Arn
      Export:
        Name: ${self:service}-${self:provider.stage}-graphql-endpoint
    UsersTableName:
      Value: !Ref UsersTable
      Export:
        Name: ${self:service}-${self:provider.stage}-users-table
    DashboardTableName:
      Value: !Ref DashboardTable
      Export:
        Name: ${self:service}-${self:provider.stage}-dashboard-table
